version: "3"
services:
    db:
        image: mysql:5
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: database
        volumes:
            - ../var/mysql:/var/lib/mysql
        networks:
            - symfony

    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080
        depends_on:
            - db
        networks:
            - symfony

    front:
        build: images/front
        ports:
            - ${WEB_PORT}:80
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ../app:/var/www/app
        working_dir: /var/www/app
        networks:
            - symfony

networks:
    symfony:
        external: true
